### ISSUE TITLE
Ignore invalid headers (userproperties)

### ISSUE THREAD

**Issue by fabio-percivaldi** [rond-authz/rond#69]
**Is your feature request related to a problem? Please describe.**
When using rond without authorization-service no one correctly configure the user properties header and the marshaling fails
this is the error:
```
[1663171414738] ERROR: failed rego query input creation
    reqId: "1962aee47a138892b03e57a7b29a87ef"
    error: {
      "message": "user properties header is not valid: json: cannot unmarshal number into Go value of type map[string]interface {}"
    }
```
**Describe the solution you'd like**
rond should ignore invalid header and evaluate the expression

**Comment by fredmaggiowski** [comment]
We can make the value unmarshal optional whenever we find an empty header and then let the policy decide whether it is fine not having user properties or not.

However here the error is stating that the unmarshal operation is receiving a number (`json: cannot unmarshal number into Go value of type map`), is it supposed to be so? Can you provide us details about the value the header has? 

Is that a valid value for you? If so, I guess we should find a different solution, since I believe that an invalid value for Rönd should cause such an error, instead.

**Comment by fabio-percivaldi** [comment]
i'm not sure of where the header is taking the value from, my architecture is composed by `api-gateway` -> `rond` -> `nodejs-hello-world` there is nothing in between api gateway and rond so i think no one is populating the header with a number. This is the CURL that cause the error:
curl --request GET \
  --url 'https://training-dev.taringa-f44fb7.gcp.mia-platform.eu/node-api/hello?who=World' \
  --header 'Accept: application/json' \
  --header 'secret: <api-key>'

**Comment by davidebianchi** [comment]
If this is solved, we could add to the docs the use case when an API contains both public and private information. So, the API should handle both authenticated and unauthenticated request

**Comment by fredmaggiowski** [comment]
@fabio-percivaldi as you can see with PR #70 I've added a test case to verify the behaviour with empty header, the solution suggested by @davidebianchi in your [discussion](https://github.com/mia-platform/community/discussions/29#discussioncomment-3652548) should be enough for your use case
