### ISSUE TITLE
Plugin model definition

### ISSUE THREAD

**Issue by allevo** [rond-authz/rond#77]
# Is your feature request related to a problem? Please describe.

This application is amazing but the released package contains a lot of stuff that probably I really don't need. For example Mongo connection, crud invocation, (mia-)platform specific header management.

This impact a lot:
- debugging: the code is bigger that expected and the navigation became difficult on code growth
- develop new functionalities: the code is the same so conflicts are possibile and the isolation can be leak
- fix bugs
- size of application: the dependencies can grown on adding functionality you don't want
- security risk: lot of dependencies means more security issues to fix
- documentation: lot functionality means a lot of documentation in the same place

# Describe the solution you'd like

Different solutions are available for fixing this problem. With a *really short* research the main 2 alternatives I found are:
- go runtime plugin (https://pkg.go.dev/plugin)
- making `Rönd` a library (or a framework)

In both cases I, as developer, can define which plugin i want to have, developing my own one without breaking the other ones.

## go runtime plugin (https://pkg.go.dev/plugin)
Unfortunately go doesn't support FFI for many reason (GC etc...). But fortunately starting from a "recent" (1.9) version, go has a go native ways to load a Unix shared object.
So, I, as developer, can create my plugin define my special function (for example `find_one`) by my own and instruct `Rönd` to load it

I'm making a bigger example (NB: I'm not a compiler)

my library: rond-mongo
```go
package main

var MongoFindOneDecl = &ast.Builtin{
	Name: "find_one",
	Decl: types.NewFunction(
		types.Args(
			types.S, // collectionName
			types.A, // query
		),
		types.A, // found document
	),
}

// function loaded by Rond
var Function = rego.Function2(
	&rego.Function{
		Name: MongoFindOneDecl.Name,
		Decl: MongoFindOneDecl.Decl,
	},
	func(ctx rego.BuiltinContext, collectionNameTerm, queryTerm *ast.Term) (*ast.Term, error) {
		.... // do your stuff here
		return ast.NewTerm(t), nil
	},
)

// function loaded by Rond
func Startup(ctx context.Context) error {
  // add mongoclient to context
  return nil
}

```

Build my library:
```
go build -buildmode=plugin
```

Load in `Rönd` the plugins
```go
plugin_paths := strings.Split(env.PluginPaths, ",")
for _, plugin_path := range plugin_paths {
    p, err := plugin.Open(plugin_path)
    if err != nil {
	    panic(err)
    }
    v, err := p.Lookup("Function")
    if err != nil {
	    panic(err)
    }
    f, err := p.Lookup("Startup")
    if err != nil {
	    panic(err)
    }
    // store that and use in `rego.New` method
    *v.(*int)
    f.(func(context.Context))
}
```

Run `Rönd`
```
PLUGIN_PATHS="/path1/rond-mongo.so,/path2/rond-crud.so" ./rond
```

### pro / const

The runtime bindings are used for many decades and it works very well. But probably there's a reason if some products move away from a similar solution (openssl, go compiler etc...). Not so complicated to implement.
Doesn't work on Windows system

## making `Rönd` a library (or a framework)

`Rönd` can move to a library that, if configured, starts a webserver, applies rego rules and proxies the request to the target server.
So my application could seem like

```go

var MongoFindOneDecl = &ast.Builtin{
	Name: "find_one",
	Decl: types.NewFunction(
		types.Args(
			types.S, // collectionName
			types.A, // query
		),
		types.A, // found document
	),
}

var MongoFindOneFunction = rego.Function2(
	&rego.Function{
		Name: MongoFindOneDecl.Name,
		Decl: MongoFindOneDecl.Decl,
	},
	func(ctx rego.BuiltinContext, collectionNameTerm, queryTerm *ast.Term) (*ast.Term, error) {
		.... // do your stuff here
		return ast.NewTerm(t), nil
	},
)


func main() {
  // add mongoclient to context
  r := rond.New(ctx, /* parameters */, MongoFindOneFunction /* other plugin */)
  r.Start()
}
```

### pro / const

This approach reduces a lot the code but doesn't build a plugin system, so that issue still persists.
But probably that problem can be overcame move all "customer" functionality in the application. So no one should complain...

# Describe alternatives you've considered

I'm not a very expert on go, so probably there're other solutions I did't consider. Please feel free to share 😄 

# Additional context

**Comment by fredmaggiowski** [comment]
Hi @allevo, thank you for this proposal and the effort you put in it!

There are several things to discuss here so I'll try my best to categorize and address them all.

## Sidecar vs Library vs Framework

Two of the pillars that led to the creation of Rönd were:

 * to decouple security controls and application code
 * to limit the amount of code the user is required to write

The way Rönd is implemented allows users to only write security policies and then "install" them on any application service they have.

We could still export Rönd primitives as a library with a simple interface that lets you add your own builtins, but then you'd have to compile and build your own sidecar, this have great impacts on the developer experience but, since we'd still provide the container it would only affect those who want specific builtins written in Go.

## Go Plugin / Shared Objects

On a technical standpoint I love this solution however there are some issues that need to be considered:

  * give the possibility to load the shared objects in the File System with a simple configuration is cool but can raise some security concerns, a malicious actor could swap the shared object with a crafted shared object
  * for increased security the shared object could be provided in custom created docker image but wouldn't be much different from the lib approach (with added complexity of managing runtime symbols which makes me lean more towards the lib approach to be honest)

## Apparently useless stuff

You mentioned 

> the released package contains a lot of stuff that probably I really don't need. For example Mongo connection, crud invocation, (mia-)platform specific header management.

however these things are actually needed:

 * MongoDB connection is important for RBAC bindings management which is a core feature of Rönd. It is optional though, so if you don't configure it you won't have to deal with it; the fact that is MongoDB and not another DBMS is just a detail as more DBMS could be supported in the future, there's a related issue for this: https://github.com/rond-authz/rond/issues/52
 * CRUD invocation: it is useful for APIs related to bindings management, this too could be replaced with something less mia-platform-dependant (there is no issue for this but I think we can open and discuss about viable alternatives); however the feature behind the requirement is still a core feature (still optional, being related to RBAC management) and not something that I would remove from Rönd
 * mia-platform-specific headers: I agree they should be removed and replaced with something more standard (related to this topic there's another issue: https://github.com/rond-authz/rond/issues/21)
 
What do you think about this considerations?

**Comment by allevo** [comment]
Hi,
the main concert to use `Rond` is that code includes too much.

The developer should be able to bring to production what the project needs not other. The developer should check what goes to production because the maintanance / bugfixing / evolution cost a lot. And also the documentation.
Write "more" core (actually the right one) is not a problem if the "function" are installable though go package. As developer I can choose which function I need, develop my custom ones and invoke `Rond`.
I didn't see any issue in this:
- you can leverage on "marketplace" of plugins
- you can choose which of them you need
- use go package for installing it
- write a little main to configure and run `Rond`
- eventually write my custom plugin
In this way also the IT governance knows what goes to production.

NB: I'm not proposing to put `Rond` inside the application, but allow the developer to build **own** sidecar container. Obviously the sidecar container is reused among the applications that build by product.

I suggest you to not follow the "sa" path: as me and you mentioned, it could be A problem.

**Comment by fredmaggiowski** [comment]
In this sense, the lib approach could be a good strategy for what you say; we'll consider it for sure.

For what concerns MongoDB I do not agree with your considerations; as I mentioned earlier, RBAC *is* a core feature of Rönd, a Rönd-specific data model has been defined for this purpose and currently is only supported on MongoDB but this could change in the future. The point is that simple policy evaluation can be achieved by installing OPA directly in your cluster we wanted to build more on top of it since it wasn't enough for our use-case.

In regards of the CRUD I partially agree, CRUDs also exist outside of Mia-Platform. The CRUD integration is only used for APIs to grant and revoke bindings, for sure it can be better generalized when support for different data store for bindings will be supported.

Please note that these features **are not** used during policy evaluation (though MongoDB integration can be used if you configure it and actively use the `find_one` and `find_many` builtin functions in your policies).

**Comment by allevo** [comment]
Hi,
  sorry for continue this discussion but I'm not agree with your view: inside the JWT there're the groups of the user.
Base on the groups, the policy can evaluate without external interaction. I don't know why you need to access to external resource for knowing which "properties" / "roles" / "groups" the user has / belong. But probably I'm missing something.

Anyway I think that `Rönd` is a great tool: it is a sidecar container that proxies all the incoming requests or blocks them.
Allow to access to external resource is a plus but I don't think it can be threated as a best practise.

**Comment by fredmaggiowski** [comment]
Hey, sorry for the delay, don't worry about keeping the discussion open :)

> inside the JWT there're the groups (or roles) of the user.

This depends on the implementation

> I don't know why you need to access to external resource for knowing which "properties" / "roles" / "groups" the user has / belong.

Rönd does not perform any means of authentication; so it relies on someone else to tell it who the user is, since this is implementation-dependant we provide a way to get such information (if you have it in your JWT than that's perfect, you won't need this feature)

> Allow to access to external resource is a plus but I don't think it can be threated as a best practise.

Nobody said it is a best practice, we ship the feature since we found it to be extremely useful, and being an opt-in feature it's up to you whether you want to pay the external interaction cost or not.

I hope I have answered your concerns :)

**Comment by fredmaggiowski** [comment]
We have started a new project for creating a Rönd SDK library, I'm closing the issue as it is stale and, I believe, addressed by the whole project; please re-open it if you have any feedback
